In [1]:
print("hello world")

hello world


### First program

In [2]:
print("Swapnith")


Swapnith


In [3]:
print("python is in my blood")

python is in my blood


### Numpy and pandas

In [4]:
#numpy -> playing with array's
#pandas -> datasets
#matlab -> data visulization
#seaborn -> data visualization
#skipy-> statistical
#sklearn -> algorithms

In [6]:
import numpy as np

In [13]:
simple_array=[1,2,3]  # one dimensional
np.array(simple_array)

array([1, 2, 3])

In [9]:
simple_array=([1,2,3],[4,5,6],[7,8,9]) # three dimensional
np.array(simple_array)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
simple_array=np.array([1,2,3])  #see the diff in paraenthesis and brackets
simple_array


array([1, 2, 3])

In [16]:
np.arange(11,30)


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [21]:
np.arange(10,100)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [22]:
np.arange(1,36,5)               #1+5:6+5:11+5:16+5:21+5:26+5

array([ 1,  6, 11, 16, 21, 26, 31])

In [23]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((100),int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones(100)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones((100),int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [28]:
np.ones((2,3),int)


array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
np.linspace(1,20,5)  #first value initial and second value output and last value number of values

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [31]:
np.linspace(1,20,9)


array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [36]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [37]:
np.random.rand(3,5)   # random values ++

array([[0.471153  , 0.78931354, 0.55843951, 0.59451421, 0.01072627],
       [0.80102006, 0.34619902, 0.06449827, 0.6196481 , 0.48738575],
       [0.76999827, 0.92698883, 0.7438547 , 0.98613421, 0.40604748]])

In [38]:
np.random.randn(4,5)  # random values + and -

array([[ 0.07476543, -1.31893554, -0.62597795, -1.39753641,  0.77720381],
       [ 1.21818586,  0.32487648,  1.94980155, -1.29287768, -0.72150126],
       [ 1.14397889,  0.92094707,  1.33920295,  0.92163515,  0.05060951],
       [-1.27475555, -1.14750739,  0.13181369,  0.2513297 ,  0.76987067]])

In [42]:
np.random.randint(8,90)

53

In [43]:
np.random.randint(1,89,6)

array([12, 54, 87, 53,  6, 30])

In [44]:
simple_array=np.arange(60)

In [47]:
simple_array.reshape(5,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [48]:
simple_array.max()

59

In [49]:
simple_array.argmax()

59

In [53]:
a=np.random.rand(2,3)
a

array([[0.72864944, 0.11482384, 0.28646544],
       [0.89938746, 0.01270617, 0.42600187]])

In [54]:
a.T

array([[0.72864944, 0.89938746],
       [0.11482384, 0.01270617],
       [0.28646544, 0.42600187]])